### ISSUE TITLE
replacing ID by context pointer for thread, parallel, task, device, ...

### ISSUE THREAD

**Issue by jprotze** [OpenMPToolsInterface/OMPT-Technical-Report#2]
This change should be integrated into the document before or during the merge with the OpenMP standard document:
- The runtime has a 8-byte field of type union{void*,uint64_t} associated with each thread/ parallel team/ task to store a value for the OMPT tool.
- This field is initialized to 0 by the runtime.
- All functions that currently have a *_id argument/return-value provide the address of this field instead.
  -> The reason for providing the address in all functions is the symmetry of begin/end functions.
- For the cases where the runtime internal data structure is invalidated, but the value is still needed for an event (Alex' scenario in earlier email discussions), the runtime should be able to store this value in a stack variable.
- the ompt_get_*_info functions can return "invalid" for cases where the value might be gone.

**Comment by AlexandreEichenberger** [comment]
One caviat with changing to "copies" is that, say for the parallel id, one thread changing a value may not be seen by the other threads.
 
So we should add a restriction to the "end" event, which states that changes to the data (pointer or interger) by one thread may not be seen by the other threads.
 
We may restrict this restriction to end barrier.
Alexandre-----------------------------------------------------------------------------------------------------Alexandre Eichenberger, Master Inventor, Advanced Compiler Technologies- research: compiler optimization (OpenMP, multithreading, SIMD)- info: alexe@us.ibm.com http://www.research.ibm.com/people/a/alexe- phone: 914-945-1812 (work) 914-312-3618 (cell)
 
 
----- Original message -----From: Joachim notifications@github.comTo: OpenMPToolsInterface/OMPT-Technical-Report OMPT-Technical-Report@noreply.github.comCc:Subject: [OpenMPToolsInterface/OMPT-Technical-Report] replacing ID by context pointer for thread, parallel, task, device, ... (#2)Date: Tue, May 24, 2016 7:34 AM 
This change should be integrated into the document before or during the merge with the OpenMP standard document:
        The runtime has a 8-byte field of type union{void_,uint64_t} associated with each thread/ parallel team/ task to store a value for the OMPT tool.        This field is initialized to 0 by the runtime.        All functions that currently have a *_id argument/return-value provide the address of this field instead. -> The reason for providing the address in all functions is the symmetry of begin/end functions.        For the cases where the runtime internal data structure is invalidated, but the value is still needed for an event (Alex' scenario in earlier email discussions), the runtime should be able to store this value in a stack variable.        the ompt_get___info functions can return "invalid" for cases where the value might be gone.

**Comment by jmellorcrummey** [comment]
My principal comment on this draft (which I haven’t yet read carefully) is that we shouldn’t have the separate typedefs for ompt_thread_data_t, ompt_task_data_t, ompt_parallel_data_t. We should just have everyone use the same base type ompt_data_t and distinguish what they mean in the callbacks by parameter names.

**Comment by jprotze** [comment]
merge completed
